### ISSUE TITLE
Progress Tracker

### ISSUE THREAD

**Issue by humblenginr** [kubevirt/k8s-seccomp-generator#2]
The `k8s_seccomp_generator` project allows the user to generate seccomp profiles based on the system calls used by one or more Kubernetes pods.

TODOs: 

- [ ] Identify the best approach to communicate with the `syscalls-tracer` pod from outside the kubernetes cluster
- [x] Develop the CLI tool 
    - This tool should replace the installation scripts 
- [ ] Add support for syscall arguments
- [ ] Look into the failure and edge case scenarios
- [x] Make sure that the solution is independent of the CRI implementation being used
- [ ] Add unit and integration tests
- [ ] Improve the `falco-syscalls-formatter` data writing logic to be more effective (https://github.com/sudo-NithishKarthik/k8s_seccomp_generator/pull/1#discussion_r1259681949)
- [ ] Automatically stop the trace when the selected pod terminates
- [ ] Support for multiple nodes
- [ ] Bundle the install manifests into a Helm chart
- [ ] Add a Demo to the README
